---

- name: Make sure Docker group exists
  group:
    name: docker
    state: present

- name: Set user {{ tezos_user }}
  user:
    name: "{{ tezos_user }}"
    shell: /bin/bash
    comment: "tezos user"
    groups: docker
  when: tezos_create_user

- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add repository 
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    state: present
    filename: 'docker'

- name: Install docker community edition
  apt:
    name: docker-ce
    state: present

- name: Make sure docker service is enable/started
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Make sure tezos install directory exists
  file:
    path: "{{ tezos_install_dir }}" 
    state: directory
    owner: root
    group: docker
    mode: 0770
  
- name: Download alphanet script from tezos github
  get_url:
    url: https://raw.githubusercontent.com/tezos/tezos/alphanet/scripts/alphanet.sh
    dest: "{{ tezos_install_dir }}"
    mode: 0755
